[package]
name = "coelho"
version = "0.1.0"
edition = "2021"
license = "BSD-3-Clause"
authors = ["Avery R. <contact@nekodjin.org>"]
repository = "https://github.com/nekodjin/coelho"
description = "Reserved for the Coelho shell language."

[dependencies]

